# Vimarsh User Feedback Collection and Continuous Improvement Configuration

feedback:
  # Collection Settings
  collection:
    enabled: true
    anonymous_allowed: true
    voice_feedback_enabled: true
    max_text_length: 5000
    max_audio_duration_seconds: 300
    
  # Feedback Types Configuration
  types:
    rating:
      enabled: true
      scale: 5  # 1-5 star rating
      require_comment_below: 3  # Require comment for ratings below 3
    
    text_feedback:
      enabled: true
      categories:
        - general
        - spiritual_accuracy
        - user_experience
        - content_quality
        - feature_request
        - bug_report
    
    voice_feedback:
      enabled: true
      auto_transcription: true
      languages:
        - en-US
        - hi-IN
      storage:
        encrypt: true
        retention_days: 365
    
    spiritual_accuracy:
      enabled: true
      expert_review_required: true
      validation_threshold: 0.8

  # Analytics Configuration
  analytics:
    enabled: true
    sentiment_analysis: true
    theme_extraction: true
    trend_analysis: true
    
    # Machine Learning Settings
    ml_processing:
      enabled: true
      models:
        sentiment: "spiritual_sentiment_v1"
        theme_extraction: "spiritual_theme_v1"
        quality_assessment: "response_quality_v1"
    
    # Privacy Settings
    privacy:
      anonymize_user_data: true
      gdpr_compliant: true
      data_retention_days: 730
      ip_anonymization: true

  # Continuous Improvement Settings
  continuous_improvement:
    enabled: true
    auto_analysis_interval_hours: 24
    improvement_threshold: 0.8
    
    # Automated Actions
    automation:
      auto_optimize: false  # Require manual approval
      alert_on_issues: true
      generate_reports: true
      
    # Improvement Categories
    categories:
      spiritual_accuracy:
        priority: critical
        threshold: 0.9
        actions:
          - expert_review
          - content_validation
          - prompt_optimization
      
      user_experience:
        priority: high
        threshold: 4.0
        actions:
          - ui_improvements
          - performance_optimization
          - user_journey_analysis
      
      performance:
        priority: medium
        threshold: 0.8
        actions:
          - system_optimization
          - response_time_improvement
          - resource_efficiency

  # Reporting Configuration
  reporting:
    enabled: true
    formats:
      - json
      - html
      - pdf
    
    schedules:
      daily:
        enabled: true
        time: "02:00"
        recipients:
          - admin@vimarsh.com
      
      weekly:
        enabled: true
        day: "sunday"
        time: "08:00"
        include_trends: true
      
      monthly:
        enabled: true
        day: 1
        comprehensive: true

  # Expert Review Integration
  expert_review:
    enabled: true
    categories:
      - spiritual_accuracy
      - content_appropriateness
      - cultural_sensitivity
    
    workflow:
      auto_trigger_threshold: 2.5  # Auto-trigger for ratings below 2.5
      review_timeout_hours: 48
      escalation_enabled: true

  # Quality Assurance
  quality_assurance:
    enabled: true
    validation_rules:
      - no_inappropriate_content
      - spiritual_alignment_check
      - factual_accuracy_verification
      - cultural_sensitivity_review
    
    thresholds:
      minimum_rating: 3.0
      spiritual_accuracy: 0.85
      response_time_ms: 5000

# Spiritual Principles Integration
spiritual_principles:
  dharmic_feedback:
    enabled: true
    principles:
      - satya: "Truth in all feedback processing"
      - ahimsa: "Non-harmful improvement recommendations"
      - seva: "Service-oriented continuous improvement"
      - dharma: "Righteous path in system evolution"
  
  guidance_integration:
    incorporate_wisdom: true
    balance_technology_spirituality: true
    user_spiritual_growth: true

# Infrastructure Settings
infrastructure:
  storage:
    type: "azure_cosmos_db"
    container: "feedback"
    partition_key: "/feedback_type"
    
  processing:
    azure_functions: true
    event_driven: true
    scalability: "consumption"
  
  security:
    encryption_at_rest: true
    encryption_in_transit: true
    access_control: "rbac"
    audit_logging: true

# Integration Settings
integrations:
  analytics_service:
    enabled: true
    endpoint: "/api/analytics"
  
  cost_management:
    enabled: true
    budget_alerts: true
    optimization_suggestions: true
  
  monitoring:
    application_insights: true
    custom_metrics: true
    dashboards: true

# Development and Testing
development:
  test_mode: false
  mock_data: false
  debug_logging: false
  
  test_feedback:
    enabled: false
    auto_generate: false
    scenarios:
      - high_rating_positive
      - low_rating_negative
      - spiritual_accuracy_concern
      - performance_issue
      - feature_request

# Compliance and Legal
compliance:
  gdpr:
    enabled: true
    data_subject_rights: true
    consent_management: true
  
  data_protection:
    anonymization: true
    pseudonymization: true
    right_to_deletion: true
  
  spiritual_content:
    authenticity_verification: true
    source_attribution: true
    expert_validation: true
