# Vimarsh Security Configuration
# Comprehensive security settings and compliance requirements

security_policies:
  # Password and Authentication Security
  authentication:
    password_requirements:
      min_length: 12
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_special_chars: true
      max_age_days: 90
      prevent_reuse: 5
    
    session_management:
      max_session_duration: "8h"
      idle_timeout: "30m"
      concurrent_sessions: 3
      secure_cookies: true
      http_only_cookies: true
      same_site: "strict"
    
    multi_factor_auth:
      required_for_admin: true
      required_for_sensitive_ops: true
      backup_codes: 10
      recovery_methods: ["email", "phone"]

  # Data Protection and Privacy
  data_protection:
    encryption:
      data_at_rest: "AES-256"
      data_in_transit: "TLS 1.2+"
      key_rotation_days: 90
      backup_encryption: true
    
    data_classification:
      public: ["marketing_content", "public_docs"]
      internal: ["logs", "metrics", "internal_docs"]
      confidential: ["user_data", "spiritual_responses"]
      restricted: ["authentication_tokens", "api_keys"]
    
    retention_policies:
      user_sessions: "24h"
      conversation_history: "1y"
      audit_logs: "7y"
      error_logs: "90d"
      backup_data: "3y"
    
    gdpr_compliance:
      data_subject_rights:
        - "access"
        - "rectification" 
        - "erasure"
        - "portability"
        - "restriction"
        - "objection"
      consent_tracking: true
      lawful_basis_documentation: true
      privacy_by_design: true

  # Spiritual Content Security
  spiritual_content:
    source_verification:
      public_domain_only: true
      attribution_required: true
      expert_review_required: true
      cultural_sensitivity_check: true
    
    content_moderation:
      inappropriate_content_detection: true
      blasphemy_prevention: true
      respectful_tone_enforcement: true
      sanskrit_accuracy_validation: true
    
    expert_validation:
      min_experts_per_review: 2
      review_timeout_days: 7
      escalation_criteria:
        - "doctrinal_accuracy"
        - "cultural_sensitivity"
        - "sanskrit_pronunciation"
      
  # Technical Security Controls
  technical_security:
    network_security:
      https_only: true
      tls_version: "1.2+"
      hsts_enabled: true
      certificate_pinning: true
      
    api_security:
      rate_limiting:
        requests_per_minute: 60
        burst_capacity: 10
        spiritual_guidance_limit: 20
      
      input_validation:
        max_query_length: 1000
        allowed_characters: "alphanumeric_unicode_punctuation"
        sql_injection_protection: true
        xss_protection: true
      
      authentication:
        token_expiry: "1h"
        refresh_token_expiry: "24h"
        jwt_algorithm: "RS256"
        issuer_validation: true
    
    infrastructure_security:
      azure_security:
        rbac_enabled: true
        network_security_groups: true
        key_vault_integration: true
        diagnostic_logging: true
        
      monitoring:
        security_alerts: true
        anomaly_detection: true
        failed_auth_tracking: true
        suspicious_activity_detection: true

# Compliance Requirements
compliance_requirements:
  gdpr:
    scope: "EU users and data"
    requirements:
      - "Privacy policy published"
      - "Consent mechanisms implemented"
      - "Data subject rights supported"
      - "Data protection officer assigned"
      - "Privacy impact assessments conducted"
      - "Breach notification procedures established"
    
    technical_measures:
      - "Pseudonymization where possible"
      - "Data minimization practices"
      - "Regular security testing"
      - "Staff training on privacy"
  
  soc2:
    scope: "Service organization controls"
    trust_criteria:
      security:
        - "Access controls implemented"
        - "Logical and physical security"
        - "System operations monitoring"
        - "Change management processes"
      
      availability:
        - "System availability monitoring"
        - "Backup and recovery procedures" 
        - "Incident response planning"
        - "Capacity management"
      
      confidentiality:
        - "Data classification system"
        - "Encryption of sensitive data"
        - "Secure data disposal"
        - "Confidentiality agreements"

  spiritual_standards:
    cultural_respect:
      - "Expert validation of all spiritual content"
      - "Accurate attribution of sacred texts"
      - "Respectful handling of religious concepts"
      - "Cultural sensitivity training for team"
    
    content_accuracy:
      - "Sanskrit pronunciation verification"
      - "Doctrinal accuracy review"
      - "Historical context validation"
      - "Cross-reference with authoritative sources"

# Security Testing Requirements
security_testing:
  static_analysis:
    tools: ["bandit", "semgrep", "eslint-security"]
    frequency: "every_commit"
    fail_build_on: ["high", "critical"]
  
  dynamic_analysis:
    tools: ["zap", "burp_suite"]
    frequency: "weekly"
    scope: ["api_endpoints", "web_application"]
  
  dependency_scanning:
    tools: ["safety", "npm_audit", "snyk"]
    frequency: "daily"
    auto_update: "patch_only"
  
  penetration_testing:
    frequency: "quarterly"
    scope: "full_application"
    third_party_required: true

# Incident Response
incident_response:
  severity_levels:
    critical:
      description: "Data breach, system compromise, service down"
      response_time: "15m"
      escalation: "immediate"
      
    high:
      description: "Security vulnerability, performance degradation"
      response_time: "1h"
      escalation: "within_2h"
      
    medium:
      description: "Minor security issue, service degradation"
      response_time: "4h"
      escalation: "within_8h"
      
    low:
      description: "Enhancement request, minor bug"
      response_time: "24h"
      escalation: "none"
  
  response_team:
    roles:
      - "Incident Commander"
      - "Security Lead"
      - "Technical Lead"
      - "Communications Lead"
      - "Legal/Compliance Lead"
  
  communication_plan:
    internal_notifications:
      - "Slack incident channel"
      - "Email to leadership"
      - "Status page updates"
    
    external_notifications:
      - "User communications"
      - "Regulatory notifications"
      - "Partner notifications"

# Security Monitoring and Alerting
monitoring:
  security_events:
    authentication_failures:
      threshold: 5
      time_window: "5m"
      severity: "medium"
    
    unusual_api_usage:
      threshold: 1000
      time_window: "1h"
      severity: "high"
    
    data_access_patterns:
      unusual_data_volume: true
      off_hours_access: true
      geographic_anomalies: true
  
  compliance_monitoring:
    gdpr_metrics:
      - "Consent collection rate"
      - "Data subject request response time"
      - "Privacy policy acceptance rate"
    
    spiritual_content_metrics:
      - "Expert review completion rate"
      - "Content accuracy scores"
      - "Cultural sensitivity ratings"

# Backup and Recovery
backup_recovery:
  backup_frequency:
    user_data: "real_time"
    conversation_history: "daily"
    application_data: "daily"
    configuration: "weekly"
  
  recovery_objectives:
    rto: "4h"  # Recovery Time Objective
    rpo: "1h"  # Recovery Point Objective
    
  testing:
    recovery_drills: "monthly"
    backup_verification: "weekly"
    disaster_simulation: "quarterly"
